CREATE TABLE alerts
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    product_id   BIGINT,
    target_price DOUBLE PRECISION,
    created_at   date,
    CONSTRAINT pk_alerts PRIMARY KEY (id)
);

CREATE TABLE discounts
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    product_id             BIGINT,
    store_id               BIGINT,
    percentage_of_discount INTEGER                                 NOT NULL,
    from_date              date,
    to_date                date,
    CONSTRAINT pk_discounts PRIMARY KEY (id)
);

CREATE TABLE product_prices
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    product_id BIGINT,
    store_id   BIGINT,
    currency   VARCHAR(255),
    price      DOUBLE PRECISION,
    start_date date,
    end_date   date,
    CONSTRAINT pk_productprices PRIMARY KEY (id)
);

CREATE TABLE products
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    product_id       VARCHAR(255),
    name             VARCHAR(255),
    category         VARCHAR(255),
    brand            VARCHAR(255),
    package_quantity DOUBLE PRECISION,
    package_unit     VARCHAR(255),
    CONSTRAINT pk_products PRIMARY KEY (id)
);

CREATE TABLE stores
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_stores PRIMARY KEY (id)
);

ALTER TABLE product_prices
    ADD CONSTRAINT uc_7a6110f37da90530763d803e9 UNIQUE (product_id, store_id, start_date);

ALTER TABLE products
    ADD CONSTRAINT uc_products_productid UNIQUE (product_id);

ALTER TABLE stores
    ADD CONSTRAINT uc_stores_name UNIQUE (name);

ALTER TABLE alerts
    ADD CONSTRAINT FK_ALERTS_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES products (id);

ALTER TABLE discounts
    ADD CONSTRAINT FK_DISCOUNTS_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES products (id);

ALTER TABLE discounts
    ADD CONSTRAINT FK_DISCOUNTS_ON_STORE FOREIGN KEY (store_id) REFERENCES stores (id);

ALTER TABLE product_prices
    ADD CONSTRAINT FK_PRODUCTPRICES_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES products (id);

ALTER TABLE product_prices
    ADD CONSTRAINT FK_PRODUCTPRICES_ON_STORE FOREIGN KEY (store_id) REFERENCES stores (id);